name: Docker Image and Publish RC

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Login DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rest-api:$(date +%s)
    
    - name: Tag
      run: docker tag rest-api:$(date +%s) ${{ secrets.DOCKER_USER }}/rest-api:$(date +%s)
      
    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKER_USER }}/rest-api:$(date +%s)
