name: Docker Image and Publish RC

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
  
    - name: Login DockerHub
      uses: docker/login-action@v1
      with:
        username: DOCKER_USER
        password: DOCKER_PASSWORD
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rest-api:$(date +%s)
      
    - name: Push Docker image to DockerHub
      run: docker push DOCKER_USER/my-repository
